# Generated by Django 6.0.1 on 2026-02-16 18:56

from django.db import migrations


def populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.create(
        name='Buddy',
        date_of_birth='2018-05-20',
        personal_photo='https://example.com/photo.jpg',
    )

def reverse_populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.filter(name='Buddy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20260131_1301'),
    ]

    operations = [
        migrations.RunPython(code=populate_pet_model, reverse_code=reverse_populate_pet_model),
    ]
