# Generated by Django 6.0.1 on 2026-02-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_comment_date_and_time_of_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
    ]
